// react/src/Components/TodoList.js
import React from 'react';
import Todo from 'Components/Todo';

export default class TodoList extends React.PureComponent {
    constructor() {
        super();
        this.state = {
            todos: [
                {
                    text: 'Hello World',
                    active: true,
                }
            ],
            filter: 1
        }
    }

    addTodo(text) {
        if (!text) {
            return;
        }

        const todos = this.state.todos.concat([
            {
                text,
                active: true
            }
        ])
        this.setState(Object.assign({}, this.state, { todos }));
    }

    toggleTodo(todoId) {
        const todo = Object.assign({}, this.state.todos[todoId], {
            active: !this.state.todos[todoId].active
        });
        const todos = [
            ...this.state.todos.slice(0, todoId),
            todo,
            ...this.state.todos.slice(todoId+1),
        ];
        this.setState(Object.assign({}, this.state, { todos }));
    }

    changeFilter(filterId) {
        this.setState(Object.assign({}, this.state, { filter: filterId }));
    }

    render() {
        return (
            <div className="jumbotron todo-list mt-3">
                <h1>Todos</h1>
                <div className="form-group">
                    <input
                        className="form-control"
                        placeholder="Create a todo"
                        onKeyPress={(e) => {
                            if (e.key == 'Enter') {
                                this.addTodo(e.currentTarget.value);
                                e.currentTarget.value = '';
                            }
                        }}
                        />
                </div>
                <div className="btn-group mb-3">
                    <button className="btn btn-default" onClick={() => this.changeFilter(0)}>All</button>
                    <button className="btn btn-default" onClick={() => this.changeFilter(1)}>Active</button>
                    <button className="btn btn-default" onClick={() => this.changeFilter(2)}>Completed</button>
                </div>
                <ul className="list-group">
                    { this.state.todos.reduce((output, todo, i) => {
                        if (this.state.filter === 0
                            || (this.state.filter === 1 && todo.active)
                            || (this.state.filter === 2 && !todo.active)) {
                            output.push((
                                <li key={i} className="list-group-item">
                                    <Todo text={todo.text} active={todo.active} click={() => this.toggleTodo(i)} />
                                </li>
                            ));

                            return output;
                        }

                        return output;
                    }, []) }
                </ul>
            </div>
        )
    }
}

// vuejs/src/todo-list/todo-list.vue
<template>
    <div class="jumbotron mt-3 container todo-list">
        <h1>Todos</h1>

        <div class="form-group">
            <input
                class="form-control"
                placeholder="Add a todo"
                v-model="newTodoText"
                v-on:keyup.enter="addTodo">
        </div>

        <div class="btn-group mb-3">
            <button class="btn btn-default" v-on:click="changeFilter(0)">All</button>
            <button class="btn btn-default" v-on:click="changeFilter(1)">Active</button>
            <button class="btn btn-default" v-on:click="changeFilter(2)">Completed</button>
        </div>

        <ul class="list-group">
            <li v-for="todo in filteredTodos" class="list-group-item">
                <label class="todo" v-bind:class="{ completed: !todo.active }">
                    <input
                        type="checkbox"
                        v-model="todo.active"
                        v-bind:true-value="false"
                        v-bind:false-value="true"> {{ todo.text }}
                </label>
            </li>
        </ul>
    </div>
</template>

<script>
    export default {
        name: 'todo-list',
        props: ['initialTodos'],
        data: function() {
            return {
                newTodoText: '',
                todos: this.initialTodos,
                filter: 0
            }
        },
        computed: {
            filteredTodos: function() {
                return this.todos.filter((todo) => {
                    return this.filter === 0
                        || (this.filter === 1 && todo.active)
                        || (this.filter === 2 && !todo.active)
                });
            }
        },
        methods: {
            addTodo: function() {
                this.todos.push({
                    text: this.newTodoText,
                    active: true,
                });

                this.newTodoText = '';
            },
            changeFilter: function(filterId) {
                this.filter = filterId;
            }
        }
    }
</script>
